import { applyOracleTemporalSession, canonicalizeOracleTemporal, classifyOracleTemporal, normalizeOracleFetchedString, oracleFetchTypeHandler, oracleTemporalExpression } from './temporal.mjs'
import { DRIVER_TIMEOUTS } from '../../request-timeouts.mjs'
import { oracleConnectionConfig, oracleIdentityMatches, readOracleIdentity } from './connection.mjs'
import { formatFetchedValue } from '../../cell-value.mjs'
import { nativeErrorText } from '../../connect-error.mjs'
import { writeDriverError } from '../sql-write-error.mjs'

const quote = value => '"' + String(value).replaceAll('"', '""') + '"'
const driverErrorFields = ['code', 'errno', 'sqlState', 'errorNum', 'fatal']

function nativeDriverError(error) {
  const next = new Error(nativeErrorText(error, '数据库没有返回错误说明。'))
  if (error && typeof error === 'object') {
    for (const key of driverErrorFields) if (error[key] != null) next[key] = error[key]
  }
  return next
}

export const sql = Object.freeze({
  id: 'oracle',
  quote,
  bindPlaceholder: position => ':' + position,
  limitClause: (limit, offset = 0) => `OFFSET ${offset} ROWS FETCH NEXT ${limit} ROWS ONLY`,
  equality: (left, placeholder) => `${left}=${placeholder}`,
  columnTypePattern: /^(?:NUMBER(?:\(\d{1,2}(?:,\d{1,2})?\))?|INTEGER|FLOAT|BINARY_FLOAT|BINARY_DOUBLE|DATE|TIMESTAMP(?:\([0-9]\))?(?: WITH TIME ZONE)?|CHAR\(\d{1,4}\)|VARCHAR2\(\d{1,5}\)|NCHAR\(\d{1,4}\)|NVARCHAR2\(\d{1,4}\)|CLOB|NCLOB|BLOB)$/,
  identityClause: ' GENERATED BY DEFAULT AS IDENTITY',
  inlineColumnComment: false,
  supportsColumnComment: true,
  writableObjectStatement: (schema, name) => ({ sql: "SELECT object_type FROM all_objects WHERE owner=:1 AND object_name=:2 AND object_type IN ('TABLE','VIEW','MATERIALIZED VIEW','SYNONYM') FETCH FIRST 1 ROWS ONLY", params: [schema, name] }),
  maxIdentifierBytes: 128,
  escapeLiteral: value => value,
  createTableSuffix: '',
  renameTable: (target, nextIdentifier) => `ALTER TABLE ${target} RENAME TO ${nextIdentifier}`,
  commentTable: (target, literal) => `COMMENT ON TABLE ${target} IS ${literal}`,
  columnDefinition: definition => `(${definition})`,
  indexName: (_identifier, qualified) => qualified,
  dropIndex: (_target, _identifier, qualified) => `DROP INDEX ${qualified}`,
  dropConstraint: (target, identifier) => `ALTER TABLE ${target} DROP CONSTRAINT ${identifier}`,
  analyzeTable: (_target, schema, table) => `BEGIN DBMS_STATS.GATHER_TABLE_STATS(ownname => '${schema.replaceAll("'", "''")}', tabname => '${table.replaceAll("'", "''")}'); END;`,
  bindValue: (column, value, placeholder) => {
    const temporal = column && classifyOracleTemporal(column)
    return temporal
      ? { value: canonicalizeOracleTemporal(column, value), expression: oracleTemporalExpression(temporal, placeholder) }
      : { value, expression: placeholder }
  },
  filterBind: (column, value, placeholder, operator) => {
    const temporal = operator !== 'contains' && classifyOracleTemporal(column)
    return temporal
      ? { value: canonicalizeOracleTemporal(column, value), expression: oracleTemporalExpression(temporal, placeholder) }
      : { value, expression: placeholder }
  },
})

async function open(credentials, timeout) {
  const oracle = (await import('oracledb')).default
  const db = await oracle.getConnection(oracleConnectionConfig(credentials))
  db.callTimeout = timeout
  return db
}

export const oracleDialect = Object.freeze({
  id: 'oracle',
  sql,
  explainMessage: 'EXPLAIN PLAN · DBMS_XPLAN · 只读会话 · 未发送 AI',
  openCatalog(credentials) {
    return open(credentials, DRIVER_TIMEOUTS.connectProbe)
  },
  openMaintenance(credentials) {
    return open(credentials, DRIVER_TIMEOUTS.maintenanceCall)
  },
  async openQuery(credentials) {
    const db = await open(credentials, DRIVER_TIMEOUTS.query)
    if (credentials.identity && !await oracleIdentityMatches(db, credentials.identity)) {
      await db.close().catch(() => {})
      throw new Error('数据库实例或账号身份发生变化，请重新连接。')
    }
    await applyOracleTemporalSession(db)
    return db
  },
  async probe(connection, _credentials, options = {}) {
    const row = await connection.execute("SELECT SYS_CONTEXT('USERENV','SERVICE_NAME') FROM DUAL")
    if (options.temporal !== false) await applyOracleTemporalSession(connection)
    return {
      version: String(connection.oracleServerVersionString || '').slice(0, 120),
      database: String(row.rows[0][0] || '').slice(0, 128),
      ...(options.identity === false ? {} : { identity: JSON.stringify(await readOracleIdentity(connection)) }),
    }
  },
  async prepareReadonly(connection, schema) {
    connection.callTimeout = DRIVER_TIMEOUTS.query
    await connection.execute('ALTER SESSION SET CURRENT_SCHEMA = ' + quote(schema))
    await connection.execute('SET TRANSACTION READ ONLY')
  },
  async reset(connection) {
    await connection.rollback()
  },
  async runSelect(connection, statement, params, limit, appendRow) {
    const oracle = (await import('oracledb')).default
    let result
    try {
      result = await connection.execute(statement, params, { resultSet: true, prefetchRows: Math.min(limit, 50), fetchArraySize: Math.min(limit, 50), fetchTypeHandler: oracleFetchTypeHandler(oracle) })
    } catch (error) {
      throw nativeDriverError(error)
    }
    const columns = result.metaData.map(meta => meta.name)
    const rows = []
    let bytes = 0, truncated = false
    try {
      if (columns.length > 500 || Buffer.byteLength(JSON.stringify(columns)) > 8192) throw new Error('结果字段过多或过长。')
      while (true) {
        const batch = await result.resultSet.getRows(Math.min(limit, 50))
        if (!batch.length) break
        for (const row of batch) {
          if (row.some(value => value && typeof value === 'object' && typeof value.getData === 'function')) throw new Error('此结果包含 LOB，请先选择普通字段。按需 LOB 查看尚未接入。')
          const values = row.map(value => formatFetchedValue(value, 'oracle', normalizeOracleFetchedString))
          const next = appendRow(rows, bytes, limit, values)
          bytes = next.bytes
          if (next.truncated) { truncated = true; break }
        }
        if (truncated) break
      }
    } finally { await result.resultSet.close() }
    return { columns, binaryColumns: result.metaData.flatMap((meta, index) => meta.dbType === oracle.DB_TYPE_RAW ? [index] : []), rows, truncated }
  },
  async executeExplain(connection, statement) {
    try {
      await connection.execute(statement)
      const plan = await connection.execute("SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'ALL'))")
      return {
        columns: plan.metaData.map(meta => meta.name),
        binaryColumns: [],
        rows: plan.rows.map(row => row.map(value => value === null ? null : String(value))),
      }
    } catch (error) {
      throw nativeDriverError(error)
    }
  },
  async prepareWrite(connection, schema) {
    await connection.execute('ALTER SESSION SET CURRENT_SCHEMA = ' + quote(schema))
  },
  async verifyWritableTargets(connection, targets, assertWritableTargets) {
    return assertWritableTargets('oracle', targets, async (statement, binds) => (await connection.execute(statement, binds)).rows)
  },
  async executeWrite(connection, statement) {
    try {
      const result = await connection.execute(statement, [], { autoCommit: true })
      return Number(result?.rowsAffected ?? 0)
    } catch (error) {
      throw writeDriverError(error, nativeErrorText(error, '数据库没有返回错误说明。'))
    }
  },
  cancel(connection) {
    connection?.break?.()
  },
  async destroy(connection) {
    if (connection) await connection.close().catch(() => {})
  },
})
