export type RedisCommandHelp = { summary: string; parameters: string; result: string; example: string }

/** Chinese explanations for every command offered by the completion list. */
export const REDIS_HELP: Record<string, RedisCommandHelp> = {
  ACL: { summary: '查看或管理 Redis 用户与权限。', parameters: '先写子命令；查询用户可用 GETUSER，查看当前身份可用 WHOAMI。', result: '返回用户、权限规则或操作状态，取决于子命令。', example: 'ACL WHOAMI' },
  AUTH: { summary: '使用用户名和密码重新认证当前命令连接。', parameters: '可以只写密码，也可以先写用户名再写密码；密码不要保存在命令历史中。', result: '认证成功返回 OK，失败返回错误。', example: 'AUTH appuser your-password' },
  CLIENT: { summary: '查看或调整当前 Redis 客户端信息。', parameters: '先选子命令；LIST 查看连接，INFO 查看当前连接，SETNAME 设置名称。', result: '返回连接信息或操作状态。', example: 'CLIENT INFO' },
  CONFIG: { summary: '读取或修改 Redis 服务器配置。', parameters: 'GET 后写配置项模式；SET 后写配置项和值。修改配置可能影响整个服务。', result: 'GET 返回配置项，SET 等操作返回状态。', example: 'CONFIG GET maxmemory' },
  DBSIZE: { summary: '统计当前 DB 的 Key 数量。', parameters: '不需要参数；只统计当前连接选中的 DB。', result: '返回一个整数。', example: 'DBSIZE' },
  DECR: { summary: '将 Key 保存的整数减一。', parameters: '写一个 Key；值需要是可解析的整数。', result: '返回减少后的整数。', example: 'DECR counter' },
  DEL: { summary: '删除一个或多个 Key。', parameters: '依次写要删除的 Key；不存在的 Key 会被忽略。', result: '返回实际删除的 Key 数量。', example: 'DEL cache:a cache:b' },
  ECHO: { summary: '让 Redis 原样返回一段文本。', parameters: '写要返回的文本；包含空格时用引号包住。', result: '返回输入的文本。', example: 'ECHO "hello world"' },
  EVAL: { summary: '在 Redis 服务器执行一段 Lua 脚本。', parameters: '先写脚本，再写 Key 数量，然后依次写 Key 和其他参数；脚本可能修改数据。', result: '返回脚本自身产生的结果。', example: 'EVAL "return 1" 0' },
  EXISTS: { summary: '检查一个或多个 Key 是否存在。', parameters: '依次写要检查的 Key；重复的 Key 会按输入次数计算。', result: '返回存在的 Key 数量。', example: 'EXISTS user:1 user:2' },
  EXPIRE: { summary: '给 Key 设置按秒计算的过期时间。', parameters: '写 Key 和秒数；NX、XX、GT、LT 可限制何时更新过期时间。', result: '返回是否成功设置过期时间。', example: 'EXPIRE session:1 3600' },
  FLUSHALL: { summary: '清空 Redis 实例中的所有 DB。', parameters: '不写参数立即执行；ASYNC 表示异步清理，SYNC 表示同步清理。影响整个实例。', result: '返回操作状态。', example: 'FLUSHALL ASYNC' },
  FLUSHDB: { summary: '清空当前连接选中的 DB。', parameters: '不写参数立即执行；ASYNC 表示异步清理，SYNC 表示同步清理。', result: '返回操作状态。', example: 'FLUSHDB ASYNC' },
  GET: { summary: '读取一个 String Key 的值。', parameters: '写一个 Key；若 Key 不存在则返回空值。', result: '返回字符串值或空值。', example: 'GET user:1:name' },
  HDEL: { summary: '删除 Hash 中的一个或多个字段。', parameters: '先写 Hash Key，再写字段名。', result: '返回实际删除的字段数量。', example: 'HDEL user:1 old_field' },
  HGET: { summary: '读取 Hash 中的一个字段。', parameters: '先写 Hash Key，再写字段名。', result: '返回字段值或空值。', example: 'HGET user:1 name' },
  HGETALL: { summary: '读取 Hash 的全部字段和值。', parameters: '写一个 Hash Key；大 Hash 的返回内容可能被工作台截断。', result: '返回字段和值组成的集合。', example: 'HGETALL user:1' },
  HSCAN: { summary: '按游标分批遍历 Hash 的字段。', parameters: '先写 Hash Key 和游标；MATCH 筛选字段，COUNT 是每次扫描的工作量提示。', result: '返回下一游标及本批字段和值。', example: 'HSCAN user:1 0 MATCH name*' },
  HSET: { summary: '设置 Hash 中的一个或多个字段。', parameters: '先写 Hash Key，再按“字段 值”成对输入。', result: '返回本次新增的字段数量。', example: 'HSET user:1 name Alice' },
  INCR: { summary: '将 Key 保存的整数加一。', parameters: '写一个 Key；值需要是可解析的整数。', result: '返回增加后的整数。', example: 'INCR counter' },
  INFO: { summary: '读取 Redis 服务器运行信息。', parameters: '可选写一个信息分类，例如 MEMORY 或 STATS。', result: '返回所选分类的服务器状态文本。', example: 'INFO MEMORY' },
  LPOP: { summary: '从 List 左侧取出并删除元素。', parameters: '写 List Key；可选写取出数量。', result: '返回取出的元素，空 List 返回空值。', example: 'LPOP jobs' },
  LPUSH: { summary: '从 List 左侧插入一个或多个元素。', parameters: '先写 List Key，再写元素；多个元素会依次从左侧插入。', result: '返回插入后的 List 长度。', example: 'LPUSH jobs task-1' },
  LRANGE: { summary: '读取 List 中指定下标范围的元素。', parameters: '写 List Key、起始下标和结束下标；-1 表示最后一个元素。', result: '返回范围内的元素。', example: 'LRANGE jobs 0 -1' },
  LSET: { summary: '替换 List 中指定下标的元素。', parameters: '写 List Key、下标和新元素；下标必须存在。', result: '成功返回 OK，否则返回错误。', example: 'LSET jobs 0 task-new' },
  MEMORY: { summary: '查看 Redis 内存使用情况或诊断信息。', parameters: '先选子命令；USAGE 后写 Key 可查看该 Key 的估算内存。', result: '返回内存统计、诊断文本或数值。', example: 'MEMORY USAGE user:1' },
  MGET: { summary: '一次读取多个 String Key。', parameters: '依次写要读取的 Key；不存在的 Key 对应空值。', result: '按输入顺序返回多个值。', example: 'MGET cache:a cache:b' },
  MSET: { summary: '一次设置多个 String Key。', parameters: '按“Key 值”成对输入；会覆盖已有值。', result: '成功返回 OK。', example: 'MSET cache:a one cache:b two' },
  OBJECT: { summary: '查看 Key 的内部信息。', parameters: '先选子命令，再写 Key；ENCODING 查看内部编码。', result: '返回所选信息或空值。', example: 'OBJECT ENCODING user:1' },
  PERSIST: { summary: '移除 Key 的过期时间。', parameters: '写一个 Key；成功后该 Key 不再按 TTL 自动过期。', result: '返回是否成功移除过期时间。', example: 'PERSIST session:1' },
  PING: { summary: '检查当前命令连接是否可用。', parameters: '可选写一段文本，Redis 会原样返回；不写时返回 PONG。', result: '返回 PONG 或输入文本。', example: 'PING' },
  PTTL: { summary: '查看 Key 剩余的过期时间，单位为毫秒。', parameters: '写一个 Key；不存在或未设置过期时间时返回特殊负数。', result: '返回剩余毫秒数。', example: 'PTTL session:1' },
  RPOP: { summary: '从 List 右侧取出并删除元素。', parameters: '写 List Key；可选写取出数量。', result: '返回取出的元素，空 List 返回空值。', example: 'RPOP jobs' },
  RPUSH: { summary: '从 List 右侧插入一个或多个元素。', parameters: '先写 List Key，再写元素。', result: '返回插入后的 List 长度。', example: 'RPUSH jobs task-1' },
  SADD: { summary: '向 Set 中加入一个或多个成员。', parameters: '先写 Set Key，再写成员；已有成员不会重复加入。', result: '返回本次新增的成员数量。', example: 'SADD tags red blue' },
  SCAN: { summary: '按游标分批遍历当前 DB 的 Key。', parameters: '先写游标，首次使用 0；MATCH 筛选 Key，COUNT 只是扫描工作量提示。', result: '返回下一游标及本批 Key，可能有空页或重复项。', example: 'SCAN 0 MATCH user:* COUNT 100' },
  SCRIPT: { summary: '加载、检查或清理 Redis 脚本缓存。', parameters: '先选子命令；LOAD 后写 Lua 脚本，FLUSH 会清理脚本缓存。', result: '返回脚本摘要、存在状态或操作状态。', example: 'SCRIPT EXISTS abc123' },
  SELECT: { summary: '切换当前命令连接使用的 DB 编号。', parameters: '写 DB 编号；本工作台每次命令使用独立连接，切换不会影响下一条命令。', result: '成功返回 OK。', example: 'SELECT 1' },
  SET: { summary: '写入或覆盖一个 String Key。', parameters: '先写 Key 和值；NX 仅在不存在时写，XX 仅在存在时写，EX/PX 设置过期时间。', result: '通常返回 OK；条件不满足时返回空值，GET 选项可返回旧值。', example: 'SET session:1 active EX 3600' },
  SMEMBERS: { summary: '读取 Set 中的全部成员。', parameters: '写一个 Set Key；大 Set 的返回内容可能被工作台截断。', result: '返回成员集合，不保证排序。', example: 'SMEMBERS tags' },
  SREM: { summary: '从 Set 中移除一个或多个成员。', parameters: '先写 Set Key，再写成员。', result: '返回实际移除的成员数量。', example: 'SREM tags red' },
  SSCAN: { summary: '按游标分批遍历 Set 成员。', parameters: '先写 Set Key 和游标；MATCH 筛选成员，COUNT 是工作量提示。', result: '返回下一游标及本批成员。', example: 'SSCAN tags 0 MATCH r*' },
  TTL: { summary: '查看 Key 剩余的过期时间，单位为秒。', parameters: '写一个 Key；不存在或未设置过期时间时返回特殊负数。', result: '返回剩余秒数。', example: 'TTL session:1' },
  TYPE: { summary: '查看 Key 存储的值类型。', parameters: '写一个 Key。', result: '返回 string、hash、list、set、zset 等类型名称。', example: 'TYPE user:1' },
  UNLINK: { summary: '异步释放一个或多个 Key。', parameters: '依次写要删除的 Key；与 DEL 一样会使 Key 不可再读取。', result: '返回实际处理的 Key 数量。', example: 'UNLINK cache:a cache:b' },
  ZADD: { summary: '向 ZSet 添加带分数的成员。', parameters: '先写 ZSet Key，再按“分数 成员”成对输入；NX/XX 等选项控制更新条件。', result: '返回新增成员数量；使用 CH/INCR 时含义会变化。', example: 'ZADD ranking 10 Alice' },
  ZRANGE: { summary: '按范围读取 ZSet 成员。', parameters: '写 ZSet Key、起始位置和结束位置；可用 WITHSCORES 一并返回分数。', result: '返回指定范围内的成员。', example: 'ZRANGE ranking 0 9 WITHSCORES' },
  ZREM: { summary: '从 ZSet 删除一个或多个成员。', parameters: '先写 ZSet Key，再写成员。', result: '返回实际删除的成员数量。', example: 'ZREM ranking Alice' },
  ZSCAN: { summary: '按游标分批遍历 ZSet 成员和分数。', parameters: '先写 ZSet Key 和游标；MATCH 筛选成员，COUNT 是工作量提示。', result: '返回下一游标及本批成员、分数。', example: 'ZSCAN ranking 0 MATCH A*' },
}

export const REDIS_SUBCOMMAND_HELP: Record<string, Record<string, string>> = {
  ACL: { CAT: '列出权限类别或某类别中的命令。', GETUSER: '查看指定用户的权限设置。', LIST: '列出用户及其规则。', USERS: '列出用户名。', WHOAMI: '查看当前认证用户名。' },
  CLIENT: { GETNAME: '读取当前连接名称。', ID: '读取当前连接 ID。', INFO: '查看当前连接的信息。', LIST: '列出客户端连接。', SETNAME: '给当前连接设置名称。' },
  CONFIG: { GET: '读取匹配的配置项。', SET: '修改服务器运行配置。', RESETSTAT: '重置统计计数。', REWRITE: '将配置改动写回配置文件。' },
  MEMORY: { DOCTOR: '分析内存使用并给出诊断建议。', STATS: '查看内存统计。', USAGE: '估算指定 Key 的内存占用。' },
  OBJECT: { ENCODING: '查看 Key 的内部编码。', FREQ: '查看访问频率计数。', IDLETIME: '查看距离上次访问的秒数。', REFCOUNT: '查看引用计数。' },
  SCRIPT: { EXISTS: '检查脚本摘要是否已缓存。', FLUSH: '清空脚本缓存。', LOAD: '将 Lua 脚本载入缓存。' },
}

export const REDIS_OPTION_HELP: Record<string, Record<string, string>> = {
  EXPIRE: { NX: '仅在还没有过期时间时设置。', XX: '仅在已有过期时间时设置。', GT: '仅在新过期时间更长时设置。', LT: '仅在新过期时间更短时设置。' },
  FLUSHALL: { ASYNC: '异步清理所有 DB。', SYNC: '同步清理所有 DB。' },
  FLUSHDB: { ASYNC: '异步清理当前 DB。', SYNC: '同步清理当前 DB。' },
  HSCAN: { MATCH: '按模式筛选字段。', COUNT: '提示每次扫描的工作量。' },
  INFO: { SERVER: '服务器信息。', CLIENTS: '客户端信息。', MEMORY: '内存信息。', PERSISTENCE: '持久化信息。', STATS: '统计信息。', REPLICATION: '复制信息。', CPU: 'CPU 信息。', KEYSPACE: '各 DB 的 Key 统计。' },
  SCAN: { MATCH: '按模式筛选 Key。', COUNT: '提示每次扫描的工作量。', TYPE: '按值类型筛选 Key。' },
  SET: { NX: '仅当 Key 不存在时写入。', XX: '仅当 Key 已存在时写入。', EX: '设置秒级过期时间，后面写秒数。', PX: '设置毫秒级过期时间，后面写毫秒数。', EXAT: '按 Unix 秒时间戳过期。', PXAT: '按 Unix 毫秒时间戳过期。', GET: '返回写入前的旧值。', KEEPTTL: '保留原有过期时间。' },
  SSCAN: { MATCH: '按模式筛选成员。', COUNT: '提示每次扫描的工作量。' },
  ZADD: { NX: '只添加新成员。', XX: '只更新已有成员。', GT: '只接受更高的分数。', LT: '只接受更低的分数。', CH: '返回发生变化的成员数量。', INCR: '把分数增量加到成员原分数上。' },
  ZRANGE: { BYSCORE: '按分数范围读取。', BYLEX: '按字典序范围读取。', REV: '逆序读取。', LIMIT: '限制返回范围，后面写偏移和数量。', WITHSCORES: '同时返回成员分数。' },
  ZSCAN: { MATCH: '按模式筛选成员。', COUNT: '提示每次扫描的工作量。' },
}
